### PR TITLE
Add a hook into the connection initialization phase

### PR DESCRIPTION
**Pull request by nikita-volkov**
Any opinions or wishes for changes on this?

@steve-chavez @robx @domenkozar

### CODE REVIEW

**Comment by steve-chavez** [comment]
@nikita-volkov What's the motivation for this PR?

**Comment by nikita-volkov** [comment]
To provide a way for the user to issue some commands on every established connection prior to it becoming available for execution of statements thru the pool. E.g., to configure connections by issuing a bunch of [`SET`](https://www.postgresql.org/docs/current/sql-set.html) commands.

**Comment by steve-chavez** [comment]
Ah nice, it enables session variables then. If the connection dies, will the session variable survive?

**Comment by nikita-volkov** [comment]
I'm not sure what you imply by connection dying and variable surviving.

The same session will be reexecuted each time a connection gets established by the pool for whatever reasons. That means that it'll be safe to assume that every connection used by the pool will be running having that session executed.

**Pull request merged**
